install: true
script:
  - echo "No Tests"
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_29d5a5f76b8b_key -iv $encrypted_29d5a5f76b8b_iv
  -in id_rsa.enc -out id_rsa -d
